# Generated by Django 4.0.6 on 2022-08-13 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.URLField(blank=True),
        ),
    ]
