# Generated by Django 4.0.6 on 2022-08-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_user_liked_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_posts',
        ),
        migrations.AddField(
            model_name='user',
            name='liked_posts',
            field=models.ManyToManyField(blank=True, related_name='liked_post', to='network.post'),
        ),
    ]
